const INIT = 'INIT';

const WAIT_FOR_DEVICE = 'WAIT_FOR_DEVICE';
const DEVICE_CAPTURED = 'DEVICE_CAPTURED';
const WAIT_FOR_DEVICE_TIMEOUT = 'WAIT_FOR_DEVICE_TIMEOUT';

const UPLOAD_IMAGE_ENTERED_BIOS = 'UPLOAD_IMAGE_ENTERED_BIOS';
const UPLOAD_IMAGE_REBOOTED = 'UPLOAD_IMAGE_REBOOTED';
const UPLOAD_IMAGE_START = 'UPLOAD_IMAGE_START';
const UPLOAD_IMAGE_WAITING_FOR_REBOOT = 'UPLOAD_IMAGE_WAITING_FOR_REBOOT';

module.exports = {
  INIT,
  WAIT_FOR_DEVICE,
  DEVICE_CAPTURED,
  WAIT_FOR_DEVICE_TIMEOUT,
  UPLOAD_IMAGE_ENTERED_BIOS,
  UPLOAD_IMAGE_REBOOTED,
  UPLOAD_IMAGE_START,
  UPLOAD_IMAGE_WAITING_FOR_REBOOT,
};
